title: "Adam Stelmaszczyk's blog"
# author: "Adam Stelmaszczyk"
description: "Blog about AI, computer science etc." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
# email: "example@mail.com"
twitter_username: "astelma1"
github_username: "AdamStelmaszczyk"
linkedin_username: "adamstelmaszczyk"

google_analytics: G-DFDJBEBZMF

theme: minima
   
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
